spring:
  application:
    name: tapntravel
  datasource:
    url: jdbc:h2:mem:tapntravel
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

app:
  input-file-path: "/Users/himadripant/hp_works/scrap/taps.csv"
  output-file-path: "/Users/himadripant/hp_works/scrap/trips.csv"
